[32m2024-09-26 12:15:42 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8d1857f6-54fe-4fa2-a846-1a8e372960b0 - 61321 - LOGS_CAPTURED - Started capturing logs in process (pid: 61321).
[32m2024-09-26 12:15:42 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8d1857f6-54fe-4fa2-a846-1a8e372960b0 - 61321 - players_file - STEP_START - Started execution of step "players_file".
[32m2024-09-26 12:15:52 -0600[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 8d1857f6-54fe-4fa2-a846-1a8e372960b0 - 61321 - players_file - STEP_FAILURE - Execution of step "players_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "players_file"::

NameError: name 'MaterializeResult' is not defined

Stack Trace:
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 477, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/stankusnt/sports_bank/sports_bank/assets/nba_players.py", line 95, in players_file
    return MaterializeResult(
           ^^^^^^^^^^^^^^^^^
[0m
